linters:
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - containedctx
    - copyloopvar  # Replacement for exportloopref (Go 1.22+)
    - decorder
    - dogsled
    - durationcheck
    - errcheck
    - errname
    - gci
    - gochecknoinits
    - gofmt
    - gofumpt
    - goimports
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - grouper
    - importas
    - ineffassign
    - makezero
    - misspell
    - noctx
    - nolintlint
    - nosprintfhostport
    - staticcheck
    - thelper
    - tparallel
    - typecheck
    - unconvert
    - unused
    - usetesting   # Replacement for tenv
    - wastedassign
    - whitespace

issues:
  exclude-files:
  - ".+\\.generated.go"

output:
  sort-results: true