{{ if .Values.config.aiApiKey }}
apiVersion: v1
kind: Secret
metadata:
  name: ai-api-token
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-2" 
data:
  apiKey: {{ .Values.config.aiApiKey | b64enc }}
{{ end }}