apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: remediation-server-binding
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-3" 
subjects:
- kind: ServiceAccount
  name: remediation-server-sa
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: remediation-server-role
  apiGroup: rbac.authorization.k8s.io