apiVersion: v1
kind: Service
metadata:
  name: k8s-agent-service
  namespace: {{ .Release.Namespace }}
spec:
  type: LoadBalancer
  selector:
    {{- include "charts.selectorLabels" . | nindent 4 }}
  ports:
  - port: {{ .Values.service.port }}
    targetPort: http