# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: Lint

permissions: {}

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  required:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0
      - name: Setup Go
        uses: actions/setup-go@3041bf56c941b39c61721a86cd11f3bb1338122a # v5.2.0
        with:
          go-version: ">=1.24.0"
      - name: Run golangci-lint for k8s-agent
        uses: golangci/golangci-lint-action@v6
        with:
          skip-cache: true
          working-directory: ./k8s-agent
      - name: Run golangci-lint for remediation-server
        uses: golangci/golangci-lint-action@v6
        with:
          skip-cache: true
          working-directory: ./remediation-server
