# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: Lint

permissions: {}

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  files-changed:
    name: Detect what files changed
    runs-on: ubuntu-latest
    timeout-minutes: 5
    outputs:
      golang: ${{ steps.filter.outputs.golang}}
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3.0.2
        id: filter
        with:
          filters: |
            golang:
              - 'k8s-agent/**'
              - 'remediation-server/**'
  required:
    needs: files-changed
    if: ${{ needs.files-changed.outputs.golang == 'true' }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0
      - name: Setup Go
        uses: actions/setup-go@3041bf56c941b39c61721a86cd11f3bb1338122a # v5.2.0
        with:
          go-version: ">=1.24.0"
      - name: Run golangci-lint for k8s-agent
        uses: golangci/golangci-lint-action@v6
        with:
          skip-cache: true
          working-directory: ./k8s-agent
          args: --timeout 15m
      - name: Run golangci-lint for remediation-server
        uses: golangci/golangci-lint-action@v6
        with:
          skip-cache: true
          working-directory: ./remediation-server
          args: --timeout 15m
