name: Build and Push Docker Image

on:
  push:
    tags:
      - 'v*' 
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to use for the Docker image (e.g., v1.0.0)'
        type: string
        required: true
        default: 'latest'  # Default tag
      dest_env:
        description: Environment to deploy
        type: choice
        options:
        - k8s_agent
        - remediation_server
        required: true


jobs:
  build-and-push-k8s-agent:
    if: ${{ inputs.dest_env == 'k8s_agent' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./k8s-agent
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/k8s-agent:latest

  build-and-push-k8s-agent:
    if: ${{ inputs.dest_env == 'k8s_agent' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./k8s-agent
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/k8s-agent:latest