name: Lint and Test Charts

on: pull_request

jobs:
  files-changed:
    name: Detect what files changed
    runs-on: ubuntu-latest
    timeout-minutes: 5
    outputs:
      charts: ${{ steps.filter.outputs.charts}}
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3.0.2
        id: filter
        with:
          filters: |
            charts:
              - 'charts/**'
  required:
    needs: files-changed
    if: ${{ needs.files-changed.outputs.charts == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 #v4.2.2
        with:
          fetch-depth: 0
      
      - uses: jlumbroso/free-disk-space@76866dbe54312617f00798d1762df7f43def6e5c # v1.2.0
        with:
          tool-cache: true
          android: true
          dotnet: true
          haskell: true
          large-packages: false
          swap-storage: false
          docker-images: true

      - name: Verify helm docs
        run: |
          make verfiy-helm